# Sublime Text installation.
---
- name: add the Sublime Text key
  apt_key:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    keyring: /etc/apt/trusted.gpg.d/sublime.gpg
    state: present

- name: add the Sublime Text repository
  copy:
    dest: /etc/apt/sources.list.d/sublime-text.list
    content: deb https://download.sublimetext.com/ apt/stable/

- apt:
    update_cache: yes

- name: install Sublime Text
  apt:
    pkg: sublime-text
    state: latest

- name: привязка текстовых файлов к Sublime Text
  ini_file:
    path: ~/.config/mimeapps.list
    section: Default Applications
    option: "{{ item }}"
    value: sublime_text.desktop;
    state: present
  with_items:
    - text/x-python
    - text/markdown
    - application/x-yaml
    - application/json
    - application/xml
    - text/css
    - text/javascript
    - application/x-httpd-php
    - text/plain
  become: false

- name: install the text_hacks plugin
  copy:
    src: text_hacks.py
    dest: ~/.config/sublime-text-3/Packages/User
  become: false

- name: Sublime Text settings
  copy:
    dest: ~/.config/sublime-text-3/Packages/User/Preferences.sublime-settings
    content: |
      {
          "font_size": 14,
          "translate_tabs_to_spaces": true,
          "auto_match_enabled": false,
          "copy_with_empty_selection": false
      }
  become: false

- name: Sublime Text hot keys
  copy:
    dest: ~/.config/sublime-text-3/Packages/User/Default (Linux).sublime-keymap
    content: |
      [
          {"keys": ["f10"], "command": "toggle_setting", "args": {"setting": "word_wrap"}},
          {"keys": ["f11"], "command": "insert_date"},
          {"keys": ["alt+-"], "command": "insert_dash"},
          {"keys": ["alt+,"], "command": "insert_left_quote"},
          {"keys": ["alt+."], "command": "insert_right_quote"},
          {"keys": ["alt+["], "command": "insert_left_brace"},
          {"keys": ["alt+]"], "command": "insert_right_brace"},
          {"keys": ["alt+c"], "command": "mark_code"}
      ]
  become: false

- include: projects.yml
